language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2

    # SDK version to compile project with
    - android-23

    # Emulator system image
    - sys-img-armeabi-v7a-android-23

before_install:
  # Get Android NDK
  - if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin -O ndk.bin; else wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86.bin -O ndk.bin; fi
  - chmod a+x ndk.bin
  - ./ndk.bin > nul
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10e
  - export PATH=${PATH}:${ANDROID_NDK_HOME}

script:
  # Build tess-two
  - cd tess-two
  - ndk-build
  - android update project --path .
  - ant release
  - cd ..
